development:
  username: ""
  password: ""
  application: ""
  worker_min_count: 0

test:
  username: ""
  password: ""
  application: ""
  worker_min_count: 0

staging:
  username: "developer@25c.com"
  password: "412e3cfcd9e2f28a49766b3552c4d539c9b662c1"
  application: "web25c-stage"
  worker_min_count: 1
  
production:
  username: "developer@25c.com"
  password: "412e3cfcd9e2f28a49766b3552c4d539c9b662c1"
  application: "web25c"
  worker_min_count: 1
  