development:
  merchant_id: E7B5HYRCLHLEU
  service_url: https://www.sandbox.paypal.com/cgi-bin/webscr
  assets_url: https://www.sandbox.paypal.com
  
test:
  merchant_id: E7B5HYRCLHLEU
  service_url: https://www.sandbox.paypal.com/cgi-bin/webscr
  assets_url: https://www.sandbox.paypal.com
  
staging:
  merchant_id: E7B5HYRCLHLEU
  service_url: https://www.sandbox.paypal.com/cgi-bin/webscr
  assets_url: https://www.sandbox.paypal.com
  
production:
  merchant_id: D8VMCXUFYGQPS
  service_url: https://www.paypal.com/cgi-bin/webscr
  assets_url: https://www.paypalobjects.com
